<a href="https://colab.research.google.com/github/Neersha/Machine-learning/blob/main/Monazite_Machine_Learning_python2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df2=pd.read_excel("PCA2.xlsx")
df2.head()

Name  207Pb/235U*      1SE  206Pb/238U*    1SE.1    Rho  \
0  KAC488-1 - 2.1 - 1-      2.75294  0.13733      0.23096  0.00656  0.570   
1  KAC488-1 - 2.2 - 1-      3.48440  0.12069      0.26563  0.00465  0.505   
2  KAC488-1 - 2.3 - 1-      4.03563  0.13430      0.28971  0.00629  0.653   
3  KAC488-1 - 2.4 - 1-      3.32172  0.18574      0.25758  0.01092  0.758   
4  KAC488-1 - 1.1 - 1-      2.73585  0.14246      0.22896  0.00670  0.562   

  Target  
0      1  
1      1  
2      1  
3      1  
4      1

In [4]:
df2.describe()

207Pb/235U*        1SE  206Pb/238U*      1SE.1        Rho
count    65.000000  65.000000    65.000000  65.000000  65.000000
mean      3.691395   0.267709     0.263459   0.010434   0.613415
std       2.018467   0.822473     0.061039   0.028322   0.105960
min       2.498830   0.064610     0.212070   0.002890   0.354000
25%       2.743180   0.100950     0.230960   0.004650   0.535000
50%       2.986110   0.122430     0.243500   0.005780   0.590000
75%       4.128460   0.152240     0.287400   0.007350   0.687000
max      16.764270   6.600140     0.660200   0.230670   0.887000

In [5]:
from sklearn.preprocessing import StandardScaler
N=StandardScaler()

In [6]:
df2.columns

Index(['Name', '207Pb/235U*', '1SE', '206Pb/238U*', '1SE.1', 'Rho', 'Target'], dtype='object')

In [7]:
df2['207Pb/235U*']

0     2.75294
1     3.48440
2     4.03563
3     3.32172
4     2.73585
       ...   
60    4.51023
61    4.65340
62    2.84391
63    4.12846
64    2.83682
Name: 207Pb/235U*, Length: 65, dtype: float64

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df2.iloc[:,1:5] = scaler.fit_transform(df2.iloc[:,1:5])

In [9]:
import numpy as np

In [10]:
covariance_matrix = np.cov([df2.iloc[:,1],df2.iloc[:,2],df2.iloc[:,3],df2.iloc[:,4],df2.iloc[:,5]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.015625   0.91220371 0.97200531 0.86523804 0.0313671 ]
 [0.91220371 1.015625   0.88159976 1.00492551 0.02826835]
 [0.97200531 0.88159976 1.015625   0.8696512  0.04765997]
 [0.86523804 1.00492551 0.8696512  1.015625   0.03602481]
 [0.0313671  0.02826835 0.04765997 0.03602481 0.0112275 ]]


In [11]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [12]:
eigen_values

array([3.77001419e+00, 2.42106665e-01, 5.48834065e-02, 4.87865845e-04,
       6.23536781e-03])

In [13]:
eigen_vectors

array([[-0.49933857, -0.47056252,  0.62756779,  0.28155571,  0.23689019],
       [-0.50608051,  0.4348403 ,  0.26950647, -0.68709476, -0.10031692],
       [-0.49585563, -0.52793097, -0.6151593 , -0.17229968, -0.25943774],
       [-0.49830545,  0.55650292, -0.27985994,  0.59670802,  0.08725903],
       [-0.01903611, -0.03283633, -0.27709636, -0.25075792,  0.92676722]])

In [15]:
pc = eigen_vectors[0:5]
pc

array([[-0.49933857, -0.47056252,  0.62756779,  0.28155571,  0.23689019],
       [-0.50608051,  0.4348403 ,  0.26950647, -0.68709476, -0.10031692],
       [-0.49585563, -0.52793097, -0.6151593 , -0.17229968, -0.25943774],
       [-0.49830545,  0.55650292, -0.27985994,  0.59670802,  0.08725903],
       [-0.01903611, -0.03283633, -0.27709636, -0.25075792,  0.92676722]])

In [19]:
transformed_df2 = np.dot(df2.iloc[:,1:6],pc.T)

In [21]:
new_df2 = pd.DataFrame(transformed_df2,columns=['PC1','PC2', 'PC3', 'PC4', 'PC5'])
new_df2['Target'] = df2['Target'].values
new_df2.head()

PC1       PC2       PC3       PC4       PC5 Target
0  0.068621  0.060572  0.522624  0.262236  0.725670      1
1  0.220553  0.074371  0.028745 -0.137517  0.517574      1
2  0.376272 -0.005454 -0.409550 -0.328909  0.524150      1
3  0.262943 -0.064356  0.004622  0.139713  0.731859      1
4  0.048708  0.056104  0.545067  0.281501  0.726112      1

from matplotlib import pyplot as plt
_df_0['PC1'].plot(kind='hist', bins=20, title='PC1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['PC2'].plot(kind='hist', bins=20, title='PC2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['PC3'].plot(kind='hist', bins=20, title='PC3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['PC4'].plot(kind='hist', bins=20, title='PC4')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='PC1', y='PC2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='PC2', y='PC3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='PC3', y='PC4', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='PC4', y='PC5', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['PC1'].plot(kind='line', figsize=(8, 4), title='PC1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['PC2'].plot(kind='line', figsize=(8, 4), title='PC2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['PC3'].plot(kind='line', figsize=(8, 4), title='PC3')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['PC4'].plot(kind='line', figsize=(8, 4), title='PC4')
plt.gca().spines[['top', 'right']].set_visible(False)

In [22]:
import plotly.express as px

In [23]:
new_df2['Target']=new_df2['Target'].astype('str')
fig=px.scatter(x=new_df2['PC1'], y=new_df2['PC2'], color=new_df2['Target'])
fig.show()